replicaCount: 1
type: app # There are app, worker, cronjob
statefulset: false 
nameOverride: "adcs-inference"

image:
  repository: asia-southeast1-docker.pkg.dev/rivalz-be/adcs/adcs-inference
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  containerPort: 3003
terminationGracePeriodSeconds: 60
imagePullSecrets: 
  - name: gar-registry

secretMounts: []
  # - name: env
  #   secretName: inference-env-secret
  #   path: /app/.env

extraEnvs: []

envFrom:
  - secretRef:
      name: adcs-inference-secrets

podAnnotations: {}
livenessProbe: []
readinessProbe: []

resources:
  limits: {}
  requests: 
    cpu: "200m"
    memory: "400Mi"

ingress:
  enabled: false
  kind: gateway ### with 2 values: gateway and ingress
  gateway: ingressgateway
  gatewayname: istio-system/rivalz-ai
  hosts: 
    - 'adcs-v2-api.rivalz.ai'
  servers: 
    - port: 30000
      name: http
      protocol: HTTP

  uri_prefix: "/" ### Please mention ending slash
  # uri_rewrite: "/"