name: ADCS CORE Pipeline

on:
  push:
    branches:
      - main
      - testnet
    paths:
      - core/**

env:
  REPO_URL: "asia-southeast1-docker.pkg.dev/rivalz-be/adcs"
  NAMESPACE: "adcs"
  KUBECONFIG: "${{ vars.ROME_KUBECONFIG }}"

jobs:
  build-and-push:
    runs-on: rivalz-be
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build core service
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 -d | docker login -u _json_key --password-stdin asia-southeast1-docker.pkg.dev
          docker push ${REPO_URL}/${SERVICE_NAME}:${commit_hash}
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV
          
  deploy core service:
    needs: build-and-push
    runs-on: rivalz-be
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "testnet" ]]; then
            NAMESPACE="testnet-adcs"
          else
            NAMESPACE="adcs"
          fi
          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
      - name: Deploy core service
        run: |
          echo "${{ vars.ROME_KUBECONFIG }}" | base64 -d >> rome_kubeconfig
          export KUBECONFIG=rome_kubeconfig
          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${REPO_URL}/${SERVICE_NAME}:${commit_hash} -n ${NAMESPACE}
          kubectl rollout status deployment/${SERVICE_NAME} -n ${NAMESPACE}
