name: ADCS-Core Multi-Service Pipeline

on:
  push:
    branches:
      - main
      - testnet

env:
  REPO_URL: "asia-southeast1-docker.pkg.dev/rivalz-be/adcs"
  NAMESPACE: "adcs"
  KUBECONFIG: "${{ vars.ROME_KUBECONFIG }}"

jobs:
  detect-changes:
    runs-on: rivalz-be
    outputs:
      open_changed: ${{ steps.filter.outputs.open_matches }}
      api_changed: ${{ steps.filter.outputs.api_matches }}
      core_changed: ${{ steps.filter.outputs.core_matches }}
      inference_changed: ${{ steps.filter.outputs.inference_matches }}
      adaptors_changed: ${{ steps.filter.outputs.adaptors_matches }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            open:
              - 'open/**'
            api:
              - 'api/**'
            core:
              - 'core/**'
            inference:
              - 'inference/**'
            adaptors:
              - 'adaptors/**'

  build-and-deploy:
    needs: detect-changes
    runs-on: rivalz-be
    env:
      REPO_URL: "asia-southeast1-docker.pkg.dev/rivalz-be/adcs"
      KUBECONFIG: "${{ vars.ROME_KUBECONFIG }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "testnet" ]]; then
            NAMESPACE="testnet-adcs"
          else
            NAMESPACE="adcs"
          fi
          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV

      - name: Debug Outputs
        run: |
          echo "open_changed: ${{ needs.detect-changes.outputs.open_changed }}"
          echo "api_changed: ${{ needs.detect-changes.outputs.api_changed }}"
          echo "core_changed: ${{ needs.detect-changes.outputs.core_changed }}"
          echo "inference_changed: ${{ needs.detect-changes.outputs.inference_changed }}"
          echo "adaptors_changed: ${{ needs.detect-changes.outputs.adaptors_changed }}"

      - name: Detect changes and build
        run: |
          if [[ "${{ needs.detect-changes.outputs.open_changed }}" == "true" ]]; then
            export SERVICE_NAME="adcs-open"
            cd open
          elif [[ "${{ needs.detect-changes.outputs.api_changed }}" == "true" ]]; then
            export SERVICE_NAME="adcs-api"
            cd api
          elif [[ "${{ needs.detect-changes.outputs.core_changed }}" == "true" ]]; then
            export SERVICE_NAME="adcs-core"
            cd core
          elif [[ "${{ needs.detect-changes.outputs.inference_changed }}" == "true" ]]; then
            export SERVICE_NAME="adcs-inference"
            cd inference
          elif [[ "${{ needs.detect-changes.outputs.adaptors_changed }}" == "true" ]]; then
            export SERVICE_NAME="adcs-adaptors"
            cd adaptors
          else
            echo "No changes detected, skipping build and deploy."
            exit 0
          fi

          commit_hash=$(git rev-parse --short $GITHUB_SHA)
          docker build -t ${REPO_URL}/${SERVICE_NAME}:${commit_hash} .
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 -d | docker login -u _json_key --password-stdin asia-southeast1-docker.pkg.dev
          docker push ${REPO_URL}/${SERVICE_NAME}:${commit_hash}
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV

      - name: Set up Kubernetes context
        run: |
          echo "${{ vars.ROME_KUBECONFIG }}" | base64 -d >> rome_kubeconfig
          export KUBECONFIG=rome_kubeconfig

      - name: Deploy ${SERVICE_NAME} to Kubernetes
        run: |
          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${REPO_URL}/${SERVICE_NAME}:${COMMIT_HASH} -n ${NAMESPACE} --kubeconfig=rome_kubeconfig
          kubectl rollout status deployment/${SERVICE_NAME}
