name: ADCS OPENAPI Pipeline

on:
  push:
    branches:
      - main
      - testnet
    paths:
      - 'open/**'
      - '.github/workflows/open-pipeline.yaml'

# Prevent concurrent deployments
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_URL: "asia-southeast1-docker.pkg.dev/rivalz-be/adcs"
  NAMESPACE: "adcs"
  KUBECONFIG: "${{ vars.ROME_KUBECONFIG }}"
  SERVICE_NAME: "adcs-open"

jobs:
  build-and-push:
    runs-on: rivalz-be
    outputs:
      commit_hash: ${{ steps.build.outputs.commit_hash }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build open service
        id: build
        run: |
          cd open
          commit_hash=$(git rev-parse --short HEAD)
          docker build -t ${REPO_URL}/${SERVICE_NAME}:${commit_hash} -t ${REPO_URL}/${SERVICE_NAME}:latest .
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 -d | docker login -u _json_key --password-stdin asia-southeast1-docker.pkg.dev
          docker push ${REPO_URL}/${SERVICE_NAME}:${commit_hash}
          docker push ${REPO_URL}/${SERVICE_NAME}:latest
          echo "commit_hash=${commit_hash}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: rivalz-be
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Rivalz-ai/rivalz-helm-chart.git"
          path: rivalz-chart
          ref: main

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "testnet" ]]; then
            echo "NAMESPACE=testnet-adcs" >> $GITHUB_ENV
          else
            echo "NAMESPACE=adcs" >> $GITHUB_ENV
          fi

      - name: Deploy open service
        run: |
          echo "${{ vars.ROME_KUBECONFIG }}" | base64 -d >> rome_kubeconfig
          export KUBECONFIG=rome_kubeconfig
          helm upgrade --install ${SERVICE_NAME} rivalz-chart -f open/values.yaml -n ${NAMESPACE} \
            --kubeconfig rome_kubeconfig \
            --set image.tag=${{ needs.build-and-push.outputs.commit_hash }} \
            --set ingress.hosts[0]=${NAMESPACE}-v2-api.rivalz.ai \
            --create-namespace
